#module path
final='infra.final'
mlogger='infra.logger'
resources='infra.resources'
adb='objects.adb'
user='infra.user'
root='users.root'
room='objects.room'
agent='infra.agent'
wcom='infra.wcom'
structure='infra.structure'
light='objects.light'
window='objects.window'
ir='objects.ir'
obj='objects.amunobj'
rootRules='users.root'
protocols='infra.protocols'
gvar='infra.gvar'
powerS='objects.powerS'
irrcv='objects.irRcv'
thermostat='objects.thermostat'
lcd='objects.lcd'
#------------------------------------------------
localIp='192.168.0.10'
remoteIp='10.242.139.148'

